package org.nulleins.modart;

import android.app.Activity;
import android.app.Dialog;
import android.content.Context;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.hardware.Sensor;
import android.hardware.SensorEvent;
import android.hardware.SensorEventListener;
import android.hardware.SensorManager;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.SeekBar;
import android.widget.Toast;
import org.nulleins.Modart.R;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class ModartActivity extends Activity {

  private static final int SHARE_REQUEST = 88;
  public static final String TAG = "MOD";
  private SensorManager mSensorManager;
  private float mAccel; // acceleration apart from gravity
  private float mAccelCurrent; // current acceleration including gravity
  private float mAccelLast; // last acceleration including gravity
  private ArtworkView artCanvas;

  @Override
  public void onCreate(final Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.main);

    mSensorManager = (SensorManager) getSystemService(Context.SENSOR_SERVICE);
    mSensorManager.registerListener(mSensorListener,
        mSensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER),
        SensorManager.SENSOR_DELAY_NORMAL);
    mAccel = 0.00f;
    mAccelCurrent = SensorManager.GRAVITY_EARTH;
    mAccelLast = SensorManager.GRAVITY_EARTH;

    artCanvas = (ArtworkView)findViewById(R.id.artcanvas);
    ((SeekBar)findViewById(R.id.seekBar)).setOnSeekBarChangeListener(
        new SeekBar.OnSeekBarChangeListener() {
          @Override
          public void onProgressChanged(final SeekBar seekBar, final int value, final boolean fromUser) {
            artCanvas.setSparsity(value);
            artCanvas.invalidate();
          }

          @Override
          public void onStartTrackingTouch(final SeekBar seekBar) {
          }

          @Override
          public void onStopTrackingTouch(final SeekBar seekBar) {
          }
        });
  }

  @Override
  public boolean onCreateOptionsMenu(final Menu menu) {
    getMenuInflater().inflate(R.menu.menu, menu);
    return super.onCreateOptionsMenu(menu);
  }

  @Override
  public boolean onOptionsItemSelected(final MenuItem item) {
    switch (item.getItemId()) {
      case R.id.menu_item_info:
        moreInfo();
        return true;
      case R.id.menu_item_share:
        shareArtwork();
        return true;
      default:
        return super.onOptionsItemSelected(item);
    }
  }

  /** display the 'more information' dialog, with buttons
    * to goto to MOMA or cancel */
  private void moreInfo() {
    final Dialog dialog = new Dialog(this);

    dialog.setContentView(R.layout.information);
    dialog.setTitle(getResources().getText(R.string.moma_dialog_title));

    dialog.findViewById(R.id.come2moma).setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(final View view) {
        gotoMoma();
      }
    });
    dialog.findViewById(R.id.procrastinate).setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(final View view) {
        dialog.cancel();
      }
    });
    dialog.show();
  }

  /** invoke the 'share' chooser to share the current art canvas */
  private void shareArtwork() {
    final Bitmap screenshot = Bitmap.createBitmap(artCanvas.getWidth(), artCanvas.getHeight(), Bitmap.Config.RGB_565);
    artCanvas.draw(new Canvas(screenshot));

    final String path = MediaStore.Images.Media.insertImage(getContentResolver(), screenshot,
        "Random Art", "Generated by Android Modart app");

    final Intent shareIntent = new Intent(android.content.Intent.ACTION_SEND)
      .setFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
      .putExtra(Intent.EXTRA_STREAM,  Uri.parse(path))
      .setType("image/png");

    startActivity(Intent.createChooser(shareIntent, getResources().getText(R.string.send_to)));
  }

  @Override
  protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    if (resultCode == RESULT_OK) {
      switch ( requestCode) {
        case SHARE_REQUEST:
          Toast.makeText(getApplicationContext(), getResources().getText(R.string.share_ok), Toast.LENGTH_SHORT).show();
          Log.d(TAG, "Share request succeeded, data=" + data);
          break;
      }
    } else {
      Toast.makeText(getApplicationContext(), getResources().getText(R.string.share_fail), Toast.LENGTH_SHORT).show();
      Log.w(TAG, "Share request failed, code="+resultCode+", data="+data);
    }
  }

  /** launch browser to MoMA page */
  private void gotoMoma() {
    final Intent browserIntent = new Intent(Intent.ACTION_VIEW,
        Uri.parse(getResources().getString(R.string.moma_landing_url)));
    startActivity(browserIntent);
  }

  private static final float SHAKE_THRESHOLD = 20.0f;

  /** handle shaking: if greater than threshold, cause the art canvas to be redrawn */
  private final SensorEventListener mSensorListener = new SensorEventListener() {
    @Override
    public void onSensorChanged(final SensorEvent se) {
      final float x = se.values[0];
      final float y = se.values[1];
      final float z = se.values[2];
      mAccelLast = mAccelCurrent;
      mAccelCurrent = (float) Math.sqrt((double) (x*x + y*y + z*z));
      final float delta = mAccelCurrent - mAccelLast;
      mAccel = mAccel * 0.9f + delta * 0.1f; // low-cut filter
      if(Math.abs(delta) > SHAKE_THRESHOLD) {
        findViewById(R.id.artcanvas).invalidate();
      }
    }

    @Override
    public void onAccuracyChanged(Sensor sensor, int accuracy) {
    }
  };

  @Override
  protected void onResume() {
    super.onResume();
    mSensorManager.registerListener(mSensorListener,
        mSensorManager.getDefaultSensor(Sensor.TYPE_ACCELEROMETER),
        SensorManager.SENSOR_DELAY_NORMAL);
  }

  @Override
  protected void onPause() {
    mSensorManager.unregisterListener(mSensorListener);
    super.onPause();
  }
}
